FROM alpine

# install GUN make, java jdk:11 and python2
RUN apk add --update make; \
    apk --no-cache add openjdk11; \
    apk --no-cache add python2

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk
ENV PATH=$JAVA_HOME/bin:$PATH

WORKDIR /app
COPY . .

CMD ["make", "test"]